# coding: utf-8

"""
    STACKIT File Storage (SFS)

    API used to create and manage NFS Shares.

    The version of the OpenAPI document: 1beta.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing_extensions import Self


class ShareExportPolicyRule(BaseModel):
    """
    ShareExportPolicyRule
    """  # noqa: E501

    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    description: Optional[StrictStr] = Field(default=None, description="Description of the Rule   (optional)")
    id: Optional[StrictStr] = Field(default=None, description="ID of the Share Export Policy Rule")
    ip_acl: Optional[List[StrictStr]] = Field(
        default=None,
        description='IP access control list, where IPs must have a subnet mask (e.g. "172.16.0.0/24" for a range of IPs,  or "172.16.0.251/32" for a specific IP)   This array cannot be empty',
        alias="ipAcl",
    )
    order: Optional[StrictInt] = Field(
        default=None,
        description="Order of the rule within a Share Export Policy. The order is used so that when a client IP matches  multiple rules, the first rule is applied   This field must be set",
    )
    read_only: Optional[StrictBool] = Field(
        default=None,
        description="Flag to indicate if client IPs matching this rule can only mount the share in read only mode   Default: false",
        alias="readOnly",
    )
    set_uuid: Optional[StrictBool] = Field(
        default=None, description="Flag to honor set UUID   Default: false", alias="setUuid"
    )
    super_user: Optional[StrictBool] = Field(
        default=None,
        description="Flag to indicate if client IPs matching this rule have root access on the Share   Default: true",
        alias="superUser",
    )
    __properties: ClassVar[List[str]] = [
        "createdAt",
        "description",
        "id",
        "ipAcl",
        "order",
        "readOnly",
        "setUuid",
        "superUser",
    ]

    @field_validator("created_at", mode="before")
    def created_at_change_year_zero_to_one(cls, value):
        """Workaround which prevents year 0 issue"""
        if isinstance(value, str):
            # Check for year "0000" at the beginning of the string
            # This assumes common date formats like YYYY-MM-DDTHH:MM:SS+00:00 or YYYY-MM-DDTHH:MM:SSZ
            if value.startswith("0000-01-01T") and re.match(
                r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\+\d{2}:\d{2}|Z)$", value
            ):
                # Workaround: Replace "0000" with "0001"
                return "0001" + value[4:]  # Take "0001" and append the rest of the string
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ShareExportPolicyRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict["description"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ShareExportPolicyRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "createdAt": obj.get("createdAt"),
                "description": obj.get("description"),
                "id": obj.get("id"),
                "ipAcl": obj.get("ipAcl"),
                "order": obj.get("order"),
                "readOnly": obj.get("readOnly"),
                "setUuid": obj.get("setUuid"),
                "superUser": obj.get("superUser"),
            }
        )
        return _obj
