# coding: utf-8

"""
    STACKIT File Storage (SFS)

    API used to create and manage NFS Shares.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing_extensions import Self

from stackit.sfs.models.share_export_policy import ShareExportPolicy


class Share(BaseModel):
    """
    Share
    """  # noqa: E501

    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    export_policy: Optional[ShareExportPolicy] = Field(
        default=None,
        description="Details of the Share Export Policy to use in the Share.   Note that if this is not set, the Share can only be mounted in read only by clients with IPs matching the  IP ACL of the Resource Pool hosting this Share",
        alias="exportPolicy",
    )
    id: Optional[StrictStr] = Field(default=None, description="ID of the Share")
    labels: Optional[Dict[str, StrictStr]] = Field(
        default=None,
        description="An optional object that represents the labels associated with the share  keys are validated using the following regex '^[\\\\p{Ll}][\\\\p{Ll}\\\\p{N}_-]*$' and cannot be empty  values are validated using the following regex '^[\\\\p{Ll}\\\\p{N}_-]*$'",
    )
    mount_path: Optional[StrictStr] = Field(
        default=None, description="Mount path of the Share, used to mount the Share", alias="mountPath"
    )
    name: Optional[StrictStr] = Field(default=None, description="Name of the Share")
    space_hard_limit_gigabytes: Optional[StrictInt] = Field(
        default=None,
        description="Space hard limit for the Share. If zero, the Share will have access to the full space of the Resource Pool it lives in.   (unit: gibibytes)",
        alias="spaceHardLimitGigabytes",
    )
    state: Optional[StrictStr] = Field(
        default=None,
        description='State of the Resource Pool Snapshot   (possible values: ["pending", "creating", "created", "error", "deleting"])',
    )
    __properties: ClassVar[List[str]] = [
        "createdAt",
        "exportPolicy",
        "id",
        "labels",
        "mountPath",
        "name",
        "spaceHardLimitGigabytes",
        "state",
    ]

    @field_validator("created_at", mode="before")
    def created_at_change_year_zero_to_one(cls, value):
        """Workaround which prevents year 0 issue"""
        if isinstance(value, str):
            # Check for year "0000" at the beginning of the string
            # This assumes common date formats like YYYY-MM-DDTHH:MM:SS+00:00 or YYYY-MM-DDTHH:MM:SSZ
            if value.startswith("0000-01-01T") and re.match(
                r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\+\d{2}:\d{2}|Z)$", value
            ):
                # Workaround: Replace "0000" with "0001"
                return "0001" + value[4:]  # Take "0001" and append the rest of the string
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Share from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of export_policy
        if self.export_policy:
            _dict["exportPolicy"] = self.export_policy.to_dict()
        # set to None if export_policy (nullable) is None
        # and model_fields_set contains the field
        if self.export_policy is None and "export_policy" in self.model_fields_set:
            _dict["exportPolicy"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Share from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "createdAt": obj.get("createdAt"),
                "exportPolicy": (
                    ShareExportPolicy.from_dict(obj["exportPolicy"]) if obj.get("exportPolicy") is not None else None
                ),
                "id": obj.get("id"),
                "labels": obj.get("labels"),
                "mountPath": obj.get("mountPath"),
                "name": obj.get("name"),
                "spaceHardLimitGigabytes": obj.get("spaceHardLimitGigabytes"),
                "state": obj.get("state"),
            }
        )
        return _obj
