# coding: utf-8

"""
    STACKIT File Storage (SFS)

    API used to create and manage NFS Shares.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self


class SnapshotPolicySchedule(BaseModel):
    """
    SnapshotPolicySchedule
    """  # noqa: E501

    count: Optional[StrictInt] = Field(default=None, description="Retention Count")
    interval: Optional[StrictStr] = Field(
        default=None, description="Interval of the Schedule (follows the cron schedule expression in Unix-like systems)"
    )
    prefix: Optional[StrictStr] = Field(
        default=None, description="Prefix used for the snapshots created by this policy"
    )
    retention_period: Optional[StrictStr] = Field(
        default=None, description='Retention Period (ISO 8601 format or "infinite")', alias="retentionPeriod"
    )
    schedule_id: Optional[StrictStr] = Field(default=None, description="ID of the Schedule", alias="scheduleId")
    __properties: ClassVar[List[str]] = ["count", "interval", "prefix", "retentionPeriod", "scheduleId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SnapshotPolicySchedule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SnapshotPolicySchedule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "count": obj.get("count"),
                "interval": obj.get("interval"),
                "prefix": obj.get("prefix"),
                "retentionPeriod": obj.get("retentionPeriod"),
                "scheduleId": obj.get("scheduleId"),
            }
        )
        return _obj
