# coding: utf-8

"""
    STACKIT Automation Service API

    API endpoints for automation management .

    The version of the OpenAPI document: 1beta.0
    Contact: support@stackit.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from stackit.automation.models.automation_triggers import AutomationTriggers
from stackit.automation.models.volume_automation_input import VolumeAutomationInput
from stackit.automation.models.volume_execution_output import VolumeExecutionOutput


class VolumeExecutionAutomation(BaseModel):
    """
    VolumeExecutionAutomation
    """  # noqa: E501

    create_time: datetime = Field(alias="createTime")
    description: Optional[StrictStr] = None
    input: Optional[VolumeAutomationInput] = None
    name: Optional[StrictStr] = None
    output: Optional[VolumeExecutionOutput] = None
    template_id: Optional[UUID] = Field(default=None, alias="templateId")
    triggers: Optional[AutomationTriggers] = None
    update_time: datetime = Field(alias="updateTime")
    __properties: ClassVar[List[str]] = [
        "createTime",
        "description",
        "input",
        "name",
        "output",
        "templateId",
        "triggers",
        "updateTime",
    ]

    @field_validator("create_time", mode="before")
    def create_time_change_year_zero_to_one(cls, value):
        """Workaround which prevents year 0 issue"""
        if isinstance(value, str):
            # Check for year "0000" at the beginning of the string
            # This assumes common date formats like YYYY-MM-DDTHH:MM:SS+00:00 or YYYY-MM-DDTHH:MM:SSZ
            if value.startswith("0000-01-01T") and re.match(
                r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\+\d{2}:\d{2}|Z)$", value
            ):
                # Workaround: Replace "0000" with "0001"
                return "0001" + value[4:]  # Take "0001" and append the rest of the string
        return value

    @field_validator("update_time", mode="before")
    def update_time_change_year_zero_to_one(cls, value):
        """Workaround which prevents year 0 issue"""
        if isinstance(value, str):
            # Check for year "0000" at the beginning of the string
            # This assumes common date formats like YYYY-MM-DDTHH:MM:SS+00:00 or YYYY-MM-DDTHH:MM:SSZ
            if value.startswith("0000-01-01T") and re.match(
                r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\+\d{2}:\d{2}|Z)$", value
            ):
                # Workaround: Replace "0000" with "0001"
                return "0001" + value[4:]  # Take "0001" and append the rest of the string
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VolumeExecutionAutomation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input
        if self.input:
            _dict["input"] = self.input.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output
        if self.output:
            _dict["output"] = self.output.to_dict()
        # override the default output from pydantic by calling `to_dict()` of triggers
        if self.triggers:
            _dict["triggers"] = self.triggers.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VolumeExecutionAutomation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "createTime": obj.get("createTime"),
                "description": obj.get("description"),
                "input": VolumeAutomationInput.from_dict(obj["input"]) if obj.get("input") is not None else None,
                "name": obj.get("name"),
                "output": VolumeExecutionOutput.from_dict(obj["output"]) if obj.get("output") is not None else None,
                "templateId": obj.get("templateId"),
                "triggers": AutomationTriggers.from_dict(obj["triggers"]) if obj.get("triggers") is not None else None,
                "updateTime": obj.get("updateTime"),
            }
        )
        return _obj
