# coding: utf-8

"""
    STACKIT Application Load Balancer Web Application Firewall API

    Generate a Web Application Firewall (WAF) to use with Application Load Balancers (ALB). The name of the WAF configuration is used in the listener of the ALB. This will activate the WAF for that ALB. An ALB with a WAF can have Managed Rule Set (MRS) and in addition can have Custom Rule Group (CRG). To create a WAF one first needs to create all the configurations that are referenced in the WAF configuration. Currently this only consists of a rule configuration, which is written in Seclang. Once all configurations are created and referenced in the WAF configuration it can be used with an ALB. Currently updating a WAF configuration will not update an existing ALB until the Load Balancer VMs are restarted.

    The version of the OpenAPI document: 1beta.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, field_validator
from pydantic_core import to_jsonable_python
from typing_extensions import Annotated, Self

from stackit.albwaf.models.mrs_rule_group import MRSRuleGroup
from stackit.albwaf.models.mrs_usage import MRSUsage


class GetManagedRuleSetResponse(BaseModel):
    """
    GetManagedRuleSetResponse returns rule configuration name and it's rules.
    """  # noqa: E501

    groups: Optional[Dict[str, MRSRuleGroup]] = Field(
        default=None,
        description="Inventory of all available Managed Rule Set groups and their current configuration. The key is the unique Group ID.",
    )
    name: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None, description="Managed rule set configuration name."
    )
    type: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None, description="Get the managed rule set type."
    )
    usage: Optional[MRSUsage] = None
    version: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Managed rule set version.")
    __properties: ClassVar[List[str]] = ["groups", "name", "type", "usage", "version"]

    @field_validator("name")
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9a-z](?:(?:[0-9a-z]|-){0,61}[0-9a-z])?$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-z](?:(?:[0-9a-z]|-){0,61}[0-9a-z])?$/")
        return value

    @field_validator("type")
    def type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(TYPE_OWASP_CRS)$", value):
            raise ValueError(r"must validate the regular expression /^(TYPE_OWASP_CRS)$/")
        return value

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["TYPE_UNSPECIFIED", "TYPE_OWASP_CRS"]):
            raise ValueError("must be one of enum values ('TYPE_UNSPECIFIED', 'TYPE_OWASP_CRS')")
        return value

    @field_validator("version")
    def version_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^v\d+\.\d+\.\d+$", value):
            raise ValueError(r"must validate the regular expression /^v\d+\.\d+\.\d+$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetManagedRuleSetResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in groups (dict)
        _field_dict = {}
        if self.groups:
            for _key_groups in self.groups:
                if self.groups[_key_groups]:
                    _field_dict[_key_groups] = self.groups[_key_groups].to_dict()
            _dict["groups"] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict["usage"] = self.usage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetManagedRuleSetResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "groups": (
                    dict((_k, MRSRuleGroup.from_dict(_v)) for _k, _v in obj["groups"].items())
                    if obj.get("groups") is not None
                    else None
                ),
                "name": obj.get("name"),
                "type": obj.get("type"),
                "usage": MRSUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None,
                "version": obj.get("version"),
            }
        )
        return _obj
