# coding: utf-8

"""
    STACKIT Application Load Balancer Web Application Firewall API

    Generate a Web Application Firewall (WAF) to use with Application Load Balancers (ALB). The name of the WAF configuration is used in the listener of the ALB. This will activate the WAF for that ALB. An ALB with a WAF can have Managed Rule Set (MRS) and in addition can have Custom Rule Group (CRG). To create a WAF one first needs to create all the configurations that are referenced in the WAF configuration. Currently this only consists of a rule configuration, which is written in Seclang. Once all configurations are created and referenced in the WAF configuration it can be used with an ALB. Currently updating a WAF configuration will not update an existing ALB until the Load Balancer VMs are restarted.

    The version of the OpenAPI document: 1beta.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from stackit.albwaf.models.crg_config_quota import CRGConfigQuota
from stackit.albwaf.models.mrs_config_quota import MRSConfigQuota
from stackit.albwaf.models.waf_config_quota import WAFConfigQuota


class Quotas(BaseModel):
    """
    Quotas holds the specific quota elements for different resources
    """  # noqa: E501

    custom_rule_group: Optional[CRGConfigQuota] = Field(default=None, alias="customRuleGroup")
    managed_rule_set: Optional[MRSConfigQuota] = Field(default=None, alias="managedRuleSet")
    web_application_firewall: Optional[WAFConfigQuota] = Field(default=None, alias="webApplicationFirewall")
    __properties: ClassVar[List[str]] = ["customRuleGroup", "managedRuleSet", "webApplicationFirewall"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Quotas from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of custom_rule_group
        if self.custom_rule_group:
            _dict["customRuleGroup"] = self.custom_rule_group.to_dict()
        # override the default output from pydantic by calling `to_dict()` of managed_rule_set
        if self.managed_rule_set:
            _dict["managedRuleSet"] = self.managed_rule_set.to_dict()
        # override the default output from pydantic by calling `to_dict()` of web_application_firewall
        if self.web_application_firewall:
            _dict["webApplicationFirewall"] = self.web_application_firewall.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Quotas from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "customRuleGroup": (
                    CRGConfigQuota.from_dict(obj["customRuleGroup"]) if obj.get("customRuleGroup") is not None else None
                ),
                "managedRuleSet": (
                    MRSConfigQuota.from_dict(obj["managedRuleSet"]) if obj.get("managedRuleSet") is not None else None
                ),
                "webApplicationFirewall": (
                    WAFConfigQuota.from_dict(obj["webApplicationFirewall"])
                    if obj.get("webApplicationFirewall") is not None
                    else None
                ),
            }
        )
        return _obj
