# coding: utf-8

"""
    STACKIT PostgreSQL Flex API

    This is the documentation for the STACKIT Postgres Flex service

    The version of the OpenAPI document: 3.0.0
    Contact: support@stackit.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class UserSort(str, Enum):
    """
    UserSort
    """

    """
    allowed enum values
    """
    ID_DOT_ASC = "id.asc"
    ID_DOT_DESC = "id.desc"
    NAME_DOT_DESC = "name.desc"
    NAME_DOT_ASC = "name.asc"
    STATE_DOT_DESC = "state.desc"
    STATE_DOT_ASC = "state.asc"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserSort from a JSON string"""
        return cls(json.loads(json_str))
