# coding: utf-8

"""
    STACKIT PostgreSQL Flex API

    This is the documentation for the STACKIT Postgres Flex service

    The version of the OpenAPI document: 3.0.0
    Contact: support@stackit.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from stackit.postgresflex.models.validation_error_validation_inner import (
    ValidationErrorValidationInner,
)


class ValidationError(BaseModel):
    """
    ValidationError
    """  # noqa: E501

    code: StrictInt = Field(description="the http error should be always 422 for validationError")
    validation: List[ValidationErrorValidationInner] = Field(
        description="errors for all fields where the error happened"
    )
    __properties: ClassVar[List[str]] = ["code", "validation"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ValidationError from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in validation (list)
        _items = []
        if self.validation:
            for _item_validation in self.validation:
                if _item_validation:
                    _items.append(_item_validation.to_dict())
            _dict["validation"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ValidationError from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "code": obj.get("code"),
                "validation": (
                    [ValidationErrorValidationInner.from_dict(_item) for _item in obj["validation"]]
                    if obj.get("validation") is not None
                    else None
                ),
            }
        )
        return _obj
