# coding: utf-8

"""
    STACKIT Marketplace API

    API to manage STACKIT Marketplace.

    The version of the OpenAPI document: 1
    Contact: marketplace@stackit.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from stackit.stackitmarketplace.models.marketplace_subscription_v1_file import (
    MarketplaceSubscriptionV1File,
)


class MarketplaceSubscriptionV1Assets(BaseModel):
    """
    MarketplaceSubscriptionV1Assets
    """  # noqa: E501

    end_user_license_agreement: Optional[MarketplaceSubscriptionV1File] = Field(
        default=None, alias="endUserLicenseAgreement"
    )
    product_description: Optional[MarketplaceSubscriptionV1File] = Field(default=None, alias="productDescription")
    service_certificate: Optional[MarketplaceSubscriptionV1File] = Field(default=None, alias="serviceCertificate")
    service_level_agreement: Optional[MarketplaceSubscriptionV1File] = Field(
        default=None, alias="serviceLevelAgreement"
    )
    __properties: ClassVar[List[str]] = [
        "endUserLicenseAgreement",
        "productDescription",
        "serviceCertificate",
        "serviceLevelAgreement",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarketplaceSubscriptionV1Assets from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of end_user_license_agreement
        if self.end_user_license_agreement:
            _dict["endUserLicenseAgreement"] = self.end_user_license_agreement.to_dict()
        # override the default output from pydantic by calling `to_dict()` of product_description
        if self.product_description:
            _dict["productDescription"] = self.product_description.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service_certificate
        if self.service_certificate:
            _dict["serviceCertificate"] = self.service_certificate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service_level_agreement
        if self.service_level_agreement:
            _dict["serviceLevelAgreement"] = self.service_level_agreement.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarketplaceSubscriptionV1Assets from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "endUserLicenseAgreement": (
                    MarketplaceSubscriptionV1File.from_dict(obj["endUserLicenseAgreement"])
                    if obj.get("endUserLicenseAgreement") is not None
                    else None
                ),
                "productDescription": (
                    MarketplaceSubscriptionV1File.from_dict(obj["productDescription"])
                    if obj.get("productDescription") is not None
                    else None
                ),
                "serviceCertificate": (
                    MarketplaceSubscriptionV1File.from_dict(obj["serviceCertificate"])
                    if obj.get("serviceCertificate") is not None
                    else None
                ),
                "serviceLevelAgreement": (
                    MarketplaceSubscriptionV1File.from_dict(obj["serviceLevelAgreement"])
                    if obj.get("serviceLevelAgreement") is not None
                    else None
                ),
            }
        )
        return _obj
