# coding: utf-8

"""
    STACKIT Marketplace API

    API to manage STACKIT Marketplace.

    The version of the OpenAPI document: 1
    Contact: marketplace@stackit.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictStr,
    field_validator,
)
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from stackit.stackitmarketplace.models.marketplace_subscription_v1_subscription_product import (
    MarketplaceSubscriptionV1SubscriptionProduct,
)


class MarketplaceSubscriptionV1Subscription(BaseModel):
    """
    MarketplaceSubscriptionV1Subscription
    """  # noqa: E501

    approval_timeout: Optional[StrictStr] = Field(
        default=None,
        description="Period between the subscription was created until the approval needs to happen.",
        alias="approvalTimeout",
    )
    auto_renewal: Optional[StrictBool] = Field(
        default=None,
        description="If true, the the subscription will extend its validity automatically at the end of the current period.",
        alias="autoRenewal",
    )
    lifecycle_state: StrictStr = Field(alias="lifecycleState")
    ordered_at: StrictStr = Field(description="When the subscription was ordered.", alias="orderedAt")
    organization_id: StrictStr = Field(description="The UUID of the organization.", alias="organizationId")
    product: MarketplaceSubscriptionV1SubscriptionProduct = Field(description="The product to the subscription.")
    project_id: StrictStr = Field(description="The UUID of the project.", alias="projectId")
    subscription_id: StrictStr = Field(description="The UUID of the subscription.", alias="subscriptionId")
    terminates_at: Optional[StrictStr] = Field(
        default=None, description="Timestamp when the subscription will finally terminate.", alias="terminatesAt"
    )
    valid_from: Optional[StrictStr] = Field(
        default=None, description="Timestamp when the subscription validity has started.", alias="validFrom"
    )
    valid_until: Optional[StrictStr] = Field(
        default=None,
        description="Timestamp when the current subscription validity will end. May be automatically renewed.",
        alias="validUntil",
    )
    __properties: ClassVar[List[str]] = [
        "approvalTimeout",
        "autoRenewal",
        "lifecycleState",
        "orderedAt",
        "organizationId",
        "product",
        "projectId",
        "subscriptionId",
        "terminatesAt",
        "validFrom",
        "validUntil",
    ]

    @field_validator("lifecycle_state")
    def lifecycle_state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(
            [
                "STATE_UNSPECIFIED",
                "SUBSCRIPTION_PENDING",
                "SUBSCRIPTION_ACTIVE",
                "SUBSCRIPTION_INACTIVE",
                "SUBSCRIPTION_CANCELLING",
                "SUBSCRIPTION_CANCELLED",
                "SUBSCRIPTION_REJECTED",
                "SUBSCRIPTION_APPROVAL_TIMED_OUT",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('STATE_UNSPECIFIED', 'SUBSCRIPTION_PENDING', 'SUBSCRIPTION_ACTIVE', 'SUBSCRIPTION_INACTIVE', 'SUBSCRIPTION_CANCELLING', 'SUBSCRIPTION_CANCELLED', 'SUBSCRIPTION_REJECTED', 'SUBSCRIPTION_APPROVAL_TIMED_OUT')"
            )
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarketplaceSubscriptionV1Subscription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "approval_timeout",
                "auto_renewal",
                "lifecycle_state",
                "ordered_at",
                "organization_id",
                "product",
                "project_id",
                "subscription_id",
                "terminates_at",
                "valid_from",
                "valid_until",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of product
        if self.product:
            _dict["product"] = self.product.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarketplaceSubscriptionV1Subscription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "approvalTimeout": obj.get("approvalTimeout"),
                "autoRenewal": obj.get("autoRenewal"),
                "lifecycleState": obj.get("lifecycleState"),
                "orderedAt": obj.get("orderedAt"),
                "organizationId": obj.get("organizationId"),
                "product": (
                    MarketplaceSubscriptionV1SubscriptionProduct.from_dict(obj["product"])
                    if obj.get("product") is not None
                    else None
                ),
                "projectId": obj.get("projectId"),
                "subscriptionId": obj.get("subscriptionId"),
                "terminatesAt": obj.get("terminatesAt"),
                "validFrom": obj.get("validFrom"),
                "validUntil": obj.get("validUntil"),
            }
        )
        return _obj
