# coding: utf-8

"""
    STACKIT Marketplace API

    API to manage STACKIT Marketplace.

    The version of the OpenAPI document: 1
    Contact: marketplace@stackit.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501 docstring might be too long

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class PriceType(str, Enum):
    """
    The product's price type.
    """

    """
    allowed enum values
    """
    CONTRACT = "CONTRACT"
    FREE = "FREE"
    FREE_TRIAL = "FREE_TRIAL"
    BYOL = "BYOL"
    PAYG = "PAYG"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PriceType from a JSON string"""
        return cls(json.loads(json_str))
