# coding: utf-8

"""
    STACKIT IaaS API

    This API allows you to create and modify IaaS resources.

    The version of the OpenAPI document: 2
    Contact: stackit-iaas@mail.schwarz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, Dict, Optional, Set, Union

from pydantic import (
    BaseModel,
    ConfigDict,
    ValidationError,
    field_validator,
)
from typing_extensions import Self

from stackit.iaas.models.create_network_ipv4_with_prefix import (
    CreateNetworkIPv4WithPrefix,
)
from stackit.iaas.models.create_network_ipv4_with_prefix_length import (
    CreateNetworkIPv4WithPrefixLength,
)


CREATENETWORKIPV4_ONE_OF_SCHEMAS = ["CreateNetworkIPv4WithPrefix", "CreateNetworkIPv4WithPrefixLength"]


class CreateNetworkIPv4(BaseModel):
    """
    The create request for an IPv4 network.
    """

    # data type: CreateNetworkIPv4WithPrefix
    oneof_schema_1_validator: Optional[CreateNetworkIPv4WithPrefix] = None
    # data type: CreateNetworkIPv4WithPrefixLength
    oneof_schema_2_validator: Optional[CreateNetworkIPv4WithPrefixLength] = None
    actual_instance: Optional[Union[CreateNetworkIPv4WithPrefix, CreateNetworkIPv4WithPrefixLength]] = None
    one_of_schemas: Set[str] = {"CreateNetworkIPv4WithPrefix", "CreateNetworkIPv4WithPrefixLength"}

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = CreateNetworkIPv4.model_construct()
        error_messages = []
        match = 0
        # validate data type: CreateNetworkIPv4WithPrefix
        if not isinstance(v, CreateNetworkIPv4WithPrefix):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CreateNetworkIPv4WithPrefix`")
        else:
            match += 1
        # validate data type: CreateNetworkIPv4WithPrefixLength
        if not isinstance(v, CreateNetworkIPv4WithPrefixLength):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CreateNetworkIPv4WithPrefixLength`")
        else:
            match += 1
        if match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in CreateNetworkIPv4 with oneOf schemas: CreateNetworkIPv4WithPrefix, CreateNetworkIPv4WithPrefixLength. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into CreateNetworkIPv4WithPrefix
        try:
            instance.actual_instance = CreateNetworkIPv4WithPrefix.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CreateNetworkIPv4WithPrefixLength
        try:
            instance.actual_instance = CreateNetworkIPv4WithPrefixLength.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into CreateNetworkIPv4 with oneOf schemas: CreateNetworkIPv4WithPrefix, CreateNetworkIPv4WithPrefixLength. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into CreateNetworkIPv4 with oneOf schemas: CreateNetworkIPv4WithPrefix, CreateNetworkIPv4WithPrefixLength. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> Optional[Union[Dict[str, Any], CreateNetworkIPv4WithPrefix, CreateNetworkIPv4WithPrefixLength]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
