# coding: utf-8

"""
    STACKIT IaaS API

    This API allows you to create and modify IaaS resources.

    The version of the OpenAPI document: 2
    Contact: stackit-iaas@mail.schwarz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, Dict, Optional, Set, Union

from pydantic import (
    BaseModel,
    ConfigDict,
    ValidationError,
    field_validator,
)
from typing_extensions import Self

from stackit.iaas.models.nexthop_blackhole import NexthopBlackhole
from stackit.iaas.models.nexthop_internet import NexthopInternet
from stackit.iaas.models.nexthop_ipv4 import NexthopIPv4
from stackit.iaas.models.nexthop_ipv6 import NexthopIPv6


ROUTENEXTHOP_ONE_OF_SCHEMAS = ["NexthopBlackhole", "NexthopIPv4", "NexthopIPv6", "NexthopInternet"]


class RouteNexthop(BaseModel):
    """
    RouteNexthop
    """

    # data type: NexthopIPv4
    oneof_schema_1_validator: Optional[NexthopIPv4] = None
    # data type: NexthopIPv6
    oneof_schema_2_validator: Optional[NexthopIPv6] = None
    # data type: NexthopInternet
    oneof_schema_3_validator: Optional[NexthopInternet] = None
    # data type: NexthopBlackhole
    oneof_schema_4_validator: Optional[NexthopBlackhole] = None
    actual_instance: Optional[Union[NexthopBlackhole, NexthopIPv4, NexthopIPv6, NexthopInternet]] = None
    one_of_schemas: Set[str] = {"NexthopBlackhole", "NexthopIPv4", "NexthopIPv6", "NexthopInternet"}

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    discriminator_value_class_map: Dict[str, str] = {}

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = RouteNexthop.model_construct()
        error_messages = []
        match = 0
        # validate data type: NexthopIPv4
        if not isinstance(v, NexthopIPv4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NexthopIPv4`")
        else:
            match += 1
        # validate data type: NexthopIPv6
        if not isinstance(v, NexthopIPv6):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NexthopIPv6`")
        else:
            match += 1
        # validate data type: NexthopInternet
        if not isinstance(v, NexthopInternet):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NexthopInternet`")
        else:
            match += 1
        # validate data type: NexthopBlackhole
        if not isinstance(v, NexthopBlackhole):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NexthopBlackhole`")
        else:
            match += 1
        if match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in RouteNexthop with oneOf schemas: NexthopBlackhole, NexthopIPv4, NexthopIPv6, NexthopInternet. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into NexthopIPv4
        try:
            instance.actual_instance = NexthopIPv4.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NexthopIPv6
        try:
            instance.actual_instance = NexthopIPv6.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NexthopInternet
        try:
            instance.actual_instance = NexthopInternet.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NexthopBlackhole
        try:
            instance.actual_instance = NexthopBlackhole.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into RouteNexthop with oneOf schemas: NexthopBlackhole, NexthopIPv4, NexthopIPv6, NexthopInternet. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into RouteNexthop with oneOf schemas: NexthopBlackhole, NexthopIPv4, NexthopIPv6, NexthopInternet. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], NexthopBlackhole, NexthopIPv4, NexthopIPv6, NexthopInternet]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
