# coding: utf-8

"""
    STACKIT Observability API

    API endpoints for Observability on STACKIT

    The version of the OpenAPI document: 1.1.1
    Contact: stackit-argus@mail.schwarz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated, Self

from stackit.observability.models.redis_check_child_response import (
    RedisCheckChildResponse,
)


class RedisCheckResponse(BaseModel):
    """
    RedisCheckResponse
    """  # noqa: E501

    message: Annotated[str, Field(min_length=1, strict=True)]
    redis_check: Optional[RedisCheckChildResponse] = Field(default=None, alias="redisCheck")
    redis_checks: Annotated[List[RedisCheckChildResponse], Field(max_length=100)] = Field(alias="redisChecks")
    __properties: ClassVar[List[str]] = ["message", "redisCheck", "redisChecks"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RedisCheckResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of redis_check
        if self.redis_check:
            _dict["redisCheck"] = self.redis_check.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in redis_checks (list)
        _items = []
        if self.redis_checks:
            for _item in self.redis_checks:
                if _item:
                    _items.append(_item.to_dict())
            _dict["redisChecks"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RedisCheckResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "message": obj.get("message"),
                "redisCheck": (
                    RedisCheckChildResponse.from_dict(obj["redisCheck"]) if obj.get("redisCheck") is not None else None
                ),
                "redisChecks": (
                    [RedisCheckChildResponse.from_dict(_item) for _item in obj["redisChecks"]]
                    if obj.get("redisChecks") is not None
                    else None
                ),
            }
        )
        return _obj
