# coding: utf-8

"""
    STACKIT Logs API

    This API provides endpoints for managing STACKIT Logs. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictStr,
    field_validator,
)
from typing_extensions import Annotated, Self


class AccessToken(BaseModel):
    """
    AccessToken
    """  # noqa: E501

    access_token: Optional[StrictStr] = Field(
        default=None, description="A generated access token. Only available on creation.", alias="accessToken"
    )
    creator: StrictStr = Field(description="The user who created the access token.")
    description: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(
        default=None, description="The description of the access token."
    )
    display_name: Annotated[str, Field(min_length=1, strict=True, max_length=32)] = Field(
        description="The displayed name of the access token.", alias="displayName"
    )
    expires: StrictBool = Field(description="Indicates if the access token can expire.")
    id: StrictStr = Field(description="An auto generated unique id which identifies the access token.")
    permissions: List[StrictStr] = Field(description="The access permissions granted to the access token.")
    status: StrictStr
    valid_until: Optional[datetime] = Field(
        default=None,
        description="The date and time util an access token is valid to (inclusively).",
        alias="validUntil",
    )
    __properties: ClassVar[List[str]] = [
        "accessToken",
        "creator",
        "description",
        "displayName",
        "expires",
        "id",
        "permissions",
        "status",
        "validUntil",
    ]

    @field_validator("display_name")
    def display_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-zA-Z][\w -]*$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z][\w -]*$/")
        return value

    @field_validator("permissions")
    def permissions_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(["read", "write"]):
                raise ValueError("each list item must be one of ('read', 'write')")
        return value

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["active", "expired"]):
            raise ValueError("must be one of enum values ('active', 'expired')")
        return value

    @field_validator("valid_until", mode="before")
    def valid_until_change_year_zero_to_one(cls, value):
        """Workaround which prevents year 0 issue"""
        if isinstance(value, str):
            # Check for year "0000" at the beginning of the string
            # This assumes common date formats like YYYY-MM-DDTHH:MM:SS+00:00 or YYYY-MM-DDTHH:MM:SSZ
            if value.startswith("0000-01-01T") and re.match(
                r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\+\d{2}:\d{2}|Z)$", value
            ):
                # Workaround: Replace "0000" with "0001"
                return "0001" + value[4:]  # Take "0001" and append the rest of the string
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccessToken from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccessToken from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "accessToken": obj.get("accessToken"),
                "creator": obj.get("creator"),
                "description": obj.get("description"),
                "displayName": obj.get("displayName"),
                "expires": obj.get("expires"),
                "id": obj.get("id"),
                "permissions": obj.get("permissions"),
                "status": obj.get("status"),
                "validUntil": obj.get("validUntil"),
            }
        )
        return _obj
