# coding: utf-8

# flake8: noqa
"""
STACKIT MSSQL Service API

This is the documentation for the STACKIT MSSQL service

The version of the OpenAPI document: 3.0.0
Contact: support@stackit.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from stackit.sqlserverflex.models.backup_running_restore import BackupRunningRestore
from stackit.sqlserverflex.models.backup_sort import BackupSort
from stackit.sqlserverflex.models.create_database_payload import CreateDatabasePayload
from stackit.sqlserverflex.models.create_database_response import CreateDatabaseResponse
from stackit.sqlserverflex.models.create_instance_payload import CreateInstancePayload
from stackit.sqlserverflex.models.create_instance_payload_network import (
    CreateInstancePayloadNetwork,
)
from stackit.sqlserverflex.models.create_instance_response import CreateInstanceResponse
from stackit.sqlserverflex.models.create_user_payload import CreateUserPayload
from stackit.sqlserverflex.models.create_user_response import CreateUserResponse
from stackit.sqlserverflex.models.database_getcollation import DatabaseGetcollation
from stackit.sqlserverflex.models.database_getcompatibility import (
    DatabaseGetcompatibility,
)
from stackit.sqlserverflex.models.database_roles import DatabaseRoles
from stackit.sqlserverflex.models.database_sort import DatabaseSort
from stackit.sqlserverflex.models.error import Error
from stackit.sqlserverflex.models.external_s3 import ExternalS3
from stackit.sqlserverflex.models.flavor_sort import FlavorSort
from stackit.sqlserverflex.models.flavor_storage_classes_storage_class import (
    FlavorStorageClassesStorageClass,
)
from stackit.sqlserverflex.models.flavor_storage_range import FlavorStorageRange
from stackit.sqlserverflex.models.get_backup_response import GetBackupResponse
from stackit.sqlserverflex.models.get_database_response import GetDatabaseResponse
from stackit.sqlserverflex.models.get_instance_response import GetInstanceResponse
from stackit.sqlserverflex.models.get_user_response import GetUserResponse
from stackit.sqlserverflex.models.instance_edition import InstanceEdition
from stackit.sqlserverflex.models.instance_encryption import InstanceEncryption
from stackit.sqlserverflex.models.instance_network import InstanceNetwork
from stackit.sqlserverflex.models.instance_network_access_scope import (
    InstanceNetworkAccessScope,
)
from stackit.sqlserverflex.models.instance_sort import InstanceSort
from stackit.sqlserverflex.models.instance_version import InstanceVersion
from stackit.sqlserverflex.models.instance_version_opt import InstanceVersionOpt
from stackit.sqlserverflex.models.list_backup import ListBackup
from stackit.sqlserverflex.models.list_backup_response import ListBackupResponse
from stackit.sqlserverflex.models.list_backups_response import ListBackupsResponse
from stackit.sqlserverflex.models.list_collations_response import ListCollationsResponse
from stackit.sqlserverflex.models.list_compatibility_response import (
    ListCompatibilityResponse,
)
from stackit.sqlserverflex.models.list_current_running_restore_jobs import (
    ListCurrentRunningRestoreJobs,
)
from stackit.sqlserverflex.models.list_database import ListDatabase
from stackit.sqlserverflex.models.list_databases_response import ListDatabasesResponse
from stackit.sqlserverflex.models.list_flavors import ListFlavors
from stackit.sqlserverflex.models.list_flavors_response import ListFlavorsResponse
from stackit.sqlserverflex.models.list_instance import ListInstance
from stackit.sqlserverflex.models.list_instances_response import ListInstancesResponse
from stackit.sqlserverflex.models.list_roles_response import ListRolesResponse
from stackit.sqlserverflex.models.list_storages_response import ListStoragesResponse
from stackit.sqlserverflex.models.list_user import ListUser
from stackit.sqlserverflex.models.list_user_response import ListUserResponse
from stackit.sqlserverflex.models.list_versions_response import ListVersionsResponse
from stackit.sqlserverflex.models.pagination import Pagination
from stackit.sqlserverflex.models.partial_update_instance_payload import (
    PartialUpdateInstancePayload,
)
from stackit.sqlserverflex.models.partial_update_instance_payload_network import (
    PartialUpdateInstancePayloadNetwork,
)
from stackit.sqlserverflex.models.replicas import Replicas
from stackit.sqlserverflex.models.reset_user_response import ResetUserResponse
from stackit.sqlserverflex.models.restore_database_from_backup_payload import (
    RestoreDatabaseFromBackupPayload,
)
from stackit.sqlserverflex.models.restore_database_from_backup_payload_source import (
    RestoreDatabaseFromBackupPayloadSource,
)
from stackit.sqlserverflex.models.s3file_info import S3fileInfo
from stackit.sqlserverflex.models.source_backup import SourceBackup
from stackit.sqlserverflex.models.source_external_s3 import SourceExternalS3
from stackit.sqlserverflex.models.state import State
from stackit.sqlserverflex.models.storage import Storage
from stackit.sqlserverflex.models.storage_create import StorageCreate
from stackit.sqlserverflex.models.storage_update import StorageUpdate
from stackit.sqlserverflex.models.trigger_restore_payload import TriggerRestorePayload
from stackit.sqlserverflex.models.update_instance_payload import UpdateInstancePayload
from stackit.sqlserverflex.models.update_instance_payload_network import (
    UpdateInstancePayloadNetwork,
)
from stackit.sqlserverflex.models.update_instance_protection_payload import (
    UpdateInstanceProtectionPayload,
)
from stackit.sqlserverflex.models.update_instance_protection_response import (
    UpdateInstanceProtectionResponse,
)
from stackit.sqlserverflex.models.user_sort import UserSort
from stackit.sqlserverflex.models.validation_error import ValidationError
from stackit.sqlserverflex.models.validation_error_validation_inner import (
    ValidationErrorValidationInner,
)
from stackit.sqlserverflex.models.version import Version
