# coding: utf-8

"""
STACKIT MSSQL Service API

This is the documentation for the STACKIT MSSQL service

The version of the OpenAPI document: 3.0.0
Contact: support@stackit.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from stackit.sqlserverflex.models.flavor_storage_classes_storage_class import (
    FlavorStorageClassesStorageClass,
)
from stackit.sqlserverflex.models.flavor_storage_range import FlavorStorageRange


class ListStoragesResponse(BaseModel):
    """
    ListStoragesResponse
    """  # noqa: E501

    storage_classes: List[FlavorStorageClassesStorageClass] = Field(
        description="maximum storage which can be ordered for the flavor in Gigabyte.", alias="storageClasses"
    )
    storage_range: FlavorStorageRange = Field(alias="storageRange")
    __properties: ClassVar[List[str]] = ["storageClasses", "storageRange"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListStoragesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in storage_classes (list)
        _items = []
        if self.storage_classes:
            for _item_storage_classes in self.storage_classes:
                if _item_storage_classes:
                    _items.append(_item_storage_classes.to_dict())
            _dict["storageClasses"] = _items
        # override the default output from pydantic by calling `to_dict()` of storage_range
        if self.storage_range:
            _dict["storageRange"] = self.storage_range.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListStoragesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "storageClasses": (
                    [FlavorStorageClassesStorageClass.from_dict(_item) for _item in obj["storageClasses"]]
                    if obj.get("storageClasses") is not None
                    else None
                ),
                "storageRange": (
                    FlavorStorageRange.from_dict(obj["storageRange"]) if obj.get("storageRange") is not None else None
                ),
            }
        )
        return _obj
