# coding: utf-8

"""
    STACKIT MSSQL Service API

    This is the documentation for the STACKIT MSSQL service

    The version of the OpenAPI document: 2.0.0
    Contact: support@stackit.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501 docstring might be too long

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class Type(str, Enum):
    """
    Type
    """

    """
    allowed enum values
    """
    NOTFOUND = "NotFound"
    CREATE = "Create"
    READ = "Read"
    DELETE = "Delete"
    UPDATE = "Update"
    VALIDATION = "Validation"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Type from a JSON string"""
        return cls(json.loads(json_str))
