# coding: utf-8

"""
    CDN API

    API used to create and manage your CDN distributions.

    The version of the OpenAPI document: 1beta.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501 docstring might be too long

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class Region(str, Enum):
    """
    The following regions exist: - `EU` - Europe - `US` - United States / North America - `AF` - Africa - `SA` - South America - `ASIA` - Asia and Oceania
    """

    """
    allowed enum values
    """
    EU = "EU"
    US = "US"
    AF = "AF"
    SA = "SA"
    ASIA = "ASIA"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Region from a JSON string"""
        return cls(json.loads(json_str))
