# coding: utf-8

"""
    STACKIT Git API

    STACKIT Git management API.

    The version of the OpenAPI document: 1beta.0.4
    Contact: git@stackit.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictStr,
    field_validator,
)
from typing_extensions import Self


class FeatureToggle(BaseModel):
    """
    Feature toggles for the instance.
    """  # noqa: E501

    default_email_notifications: Optional[StrictStr] = Field(default=None, description="Default email notifications.")
    enable_commit_signatures: Optional[StrictBool] = Field(default=None, description="Enable commit signatures.")
    enable_local_login: Optional[StrictBool] = Field(default=None, description="Enable local login.")
    __properties: ClassVar[List[str]] = [
        "default_email_notifications",
        "enable_commit_signatures",
        "enable_local_login",
    ]

    @field_validator("default_email_notifications")
    def default_email_notifications_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["enabled", "disabled", "onmention", "andyourown"]):
            raise ValueError("must be one of enum values ('enabled', 'disabled', 'onmention', 'andyourown')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeatureToggle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if default_email_notifications (nullable) is None
        # and model_fields_set contains the field
        if self.default_email_notifications is None and "default_email_notifications" in self.model_fields_set:
            _dict["default_email_notifications"] = None

        # set to None if enable_commit_signatures (nullable) is None
        # and model_fields_set contains the field
        if self.enable_commit_signatures is None and "enable_commit_signatures" in self.model_fields_set:
            _dict["enable_commit_signatures"] = None

        # set to None if enable_local_login (nullable) is None
        # and model_fields_set contains the field
        if self.enable_local_login is None and "enable_local_login" in self.model_fields_set:
            _dict["enable_local_login"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeatureToggle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "default_email_notifications": obj.get("default_email_notifications"),
                "enable_commit_signatures": obj.get("enable_commit_signatures"),
                "enable_local_login": obj.get("enable_local_login"),
            }
        )
        return _obj
