# coding: utf-8

"""
    STACKIT Git API

    STACKIT Git management API.

    The version of the OpenAPI document: 1beta.0.4
    Contact: git@stackit.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Annotated, Self


class Flavor(BaseModel):
    """
    Describes a STACKIT Git Flavor.
    """  # noqa: E501

    availability: StrictStr = Field(description="Defines the flavor availability.")
    description: StrictStr = Field(description="Flavor description.")
    display_name: StrictStr = Field(description="The display name that will be shown in the Portal.")
    id: Annotated[str, Field(strict=True, max_length=36)] = Field(description="Flavor id.")
    sku: StrictStr = Field(description="SAP article number.")
    __properties: ClassVar[List[str]] = ["availability", "description", "display_name", "id", "sku"]

    @field_validator("availability")
    def availability_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["available", "unavailable", "internal", "deprecated"]):
            raise ValueError("must be one of enum values ('available', 'unavailable', 'internal', 'deprecated')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Flavor from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Flavor from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "availability": obj.get("availability"),
                "description": obj.get("description"),
                "display_name": obj.get("display_name"),
                "id": obj.get("id"),
                "sku": obj.get("sku"),
            }
        )
        return _obj
