# coding: utf-8

# flake8: noqa
"""
    STACKIT Server Backup Management API

    API endpoints for Server Backup Operations on STACKIT Servers.

    The version of the OpenAPI document: 1.0
    Contact: support@stackit.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501 docstring might be too long


# import models into model package
from stackit.serverbackup.models.backup import Backup
from stackit.serverbackup.models.backup_job import BackupJob
from stackit.serverbackup.models.backup_properties import BackupProperties
from stackit.serverbackup.models.backup_schedule import BackupSchedule
from stackit.serverbackup.models.backup_volume_backups_inner import (
    BackupVolumeBackupsInner,
)
from stackit.serverbackup.models.create_backup_payload import CreateBackupPayload
from stackit.serverbackup.models.create_backup_schedule_payload import (
    CreateBackupSchedulePayload,
)
from stackit.serverbackup.models.enable_service_payload import EnableServicePayload
from stackit.serverbackup.models.error_response import ErrorResponse
from stackit.serverbackup.models.list_backup_schedules200_response import (
    ListBackupSchedules200Response,
)
from stackit.serverbackup.models.list_backups200_response import ListBackups200Response
from stackit.serverbackup.models.restore_backup_payload import RestoreBackupPayload
from stackit.serverbackup.models.restore_volume_backup_payload import (
    RestoreVolumeBackupPayload,
)
from stackit.serverbackup.models.update_backup_schedule_payload import (
    UpdateBackupSchedulePayload,
)
