# coding: utf-8

"""
    STACKIT VPN API

    Provision and manage STACKIT VPN gateways.  Use this API to establish secure, encrypted IPsec tunnels between your STACKIT Network Area (SNA) and external networks. The service supports the following routing architectures: - Policy-based IPsec - Static route-based IPsec - Dynamic BGP IPsec

    The version of the OpenAPI document: 1beta1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self


class APIErrorDetail(BaseModel):
    """
    APIErrorDetail
    """  # noqa: E501

    domain: StrictStr = Field(description="The domain of the error source.")
    metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Metadata contains more information. For bad requests this would be field information.",
    )
    reason: StrictStr = Field(description="The reason why the error occurs.")
    __properties: ClassVar[List[str]] = ["domain", "metadata", "reason"]

    @field_validator("reason")
    def reason_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["INVALID_FIELD", "INVALID_PATH_PARAMETER"]):
            raise ValueError("must be one of enum values ('INVALID_FIELD', 'INVALID_PATH_PARAMETER')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIErrorDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIErrorDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "domain": obj.get("domain") if obj.get("domain") is not None else "vpn.access.stackit.cloud",
                "metadata": obj.get("metadata"),
                "reason": obj.get("reason"),
            }
        )
        return _obj
