# coding: utf-8

# flake8: noqa

"""
    STACKIT MSSQL Service API

    This is the documentation for the STACKIT MSSQL service

    The version of the OpenAPI document: 2.0.0
    Contact: support@stackit.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "HostConfiguration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ACL",
    "Backup",
    "BackupListBackupsResponseGrouped",
    "CreateDatabasePayload",
    "CreateDatabaseResponse",
    "CreateInstancePayload",
    "CreateInstanceResponse",
    "CreateUserPayload",
    "CreateUserResponse",
    "DataPoint",
    "Database",
    "DatabaseDocumentationCreateDatabaseRequestOptions",
    "DatabaseOptions",
    "Flavor",
    "GetBackupResponse",
    "GetDatabaseResponse",
    "GetInstanceResponse",
    "GetUserResponse",
    "Host",
    "HostMetric",
    "Instance",
    "InstanceDocumentationACL",
    "InstanceDocumentationOptions",
    "InstanceDocumentationStorage",
    "InstanceError",
    "InstanceFlavorEntry",
    "InstanceListInstance",
    "InstanceListUser",
    "ListBackupsResponse",
    "ListCollationsResponse",
    "ListCompatibilityResponse",
    "ListDatabasesResponse",
    "ListFlavorsResponse",
    "ListInstancesResponse",
    "ListMetricsResponse",
    "ListRestoreJobsResponse",
    "ListRolesResponse",
    "ListStoragesResponse",
    "ListUsersResponse",
    "ListVersionsResponse",
    "MssqlDatabaseCollation",
    "MssqlDatabaseCompatibility",
    "PartialUpdateInstancePayload",
    "ResetUserResponse",
    "RestoreRunningRestore",
    "SingleDatabase",
    "SingleUser",
    "Storage",
    "StorageRange",
    "TriggerDatabaseRestorePayload",
    "Type",
    "UpdateInstancePayload",
    "UpdateInstanceResponse",
    "User",
    "UserResponseUser",
]

# import apis into sdk package
from stackit.sqlserverflex.api.default_api import DefaultApi as DefaultApi
from stackit.sqlserverflex.api_client import ApiClient as ApiClient

# import ApiClient
from stackit.sqlserverflex.api_response import ApiResponse as ApiResponse
from stackit.sqlserverflex.configuration import HostConfiguration as HostConfiguration
from stackit.sqlserverflex.exceptions import ApiAttributeError as ApiAttributeError
from stackit.sqlserverflex.exceptions import ApiException as ApiException
from stackit.sqlserverflex.exceptions import ApiKeyError as ApiKeyError
from stackit.sqlserverflex.exceptions import ApiTypeError as ApiTypeError
from stackit.sqlserverflex.exceptions import ApiValueError as ApiValueError
from stackit.sqlserverflex.exceptions import OpenApiException as OpenApiException

# import models into sdk package
from stackit.sqlserverflex.models.acl import ACL as ACL
from stackit.sqlserverflex.models.backup import Backup as Backup
from stackit.sqlserverflex.models.backup_list_backups_response_grouped import (
    BackupListBackupsResponseGrouped as BackupListBackupsResponseGrouped,
)
from stackit.sqlserverflex.models.create_database_payload import (
    CreateDatabasePayload as CreateDatabasePayload,
)
from stackit.sqlserverflex.models.create_database_response import (
    CreateDatabaseResponse as CreateDatabaseResponse,
)
from stackit.sqlserverflex.models.create_instance_payload import (
    CreateInstancePayload as CreateInstancePayload,
)
from stackit.sqlserverflex.models.create_instance_response import (
    CreateInstanceResponse as CreateInstanceResponse,
)
from stackit.sqlserverflex.models.create_user_payload import (
    CreateUserPayload as CreateUserPayload,
)
from stackit.sqlserverflex.models.create_user_response import (
    CreateUserResponse as CreateUserResponse,
)
from stackit.sqlserverflex.models.data_point import DataPoint as DataPoint
from stackit.sqlserverflex.models.database import Database as Database
from stackit.sqlserverflex.models.database_documentation_create_database_request_options import (
    DatabaseDocumentationCreateDatabaseRequestOptions as DatabaseDocumentationCreateDatabaseRequestOptions,
)
from stackit.sqlserverflex.models.database_options import (
    DatabaseOptions as DatabaseOptions,
)
from stackit.sqlserverflex.models.flavor import Flavor as Flavor
from stackit.sqlserverflex.models.get_backup_response import (
    GetBackupResponse as GetBackupResponse,
)
from stackit.sqlserverflex.models.get_database_response import (
    GetDatabaseResponse as GetDatabaseResponse,
)
from stackit.sqlserverflex.models.get_instance_response import (
    GetInstanceResponse as GetInstanceResponse,
)
from stackit.sqlserverflex.models.get_user_response import (
    GetUserResponse as GetUserResponse,
)
from stackit.sqlserverflex.models.host import Host as Host
from stackit.sqlserverflex.models.host_metric import HostMetric as HostMetric
from stackit.sqlserverflex.models.instance import Instance as Instance
from stackit.sqlserverflex.models.instance_documentation_acl import (
    InstanceDocumentationACL as InstanceDocumentationACL,
)
from stackit.sqlserverflex.models.instance_documentation_options import (
    InstanceDocumentationOptions as InstanceDocumentationOptions,
)
from stackit.sqlserverflex.models.instance_documentation_storage import (
    InstanceDocumentationStorage as InstanceDocumentationStorage,
)
from stackit.sqlserverflex.models.instance_error import InstanceError as InstanceError
from stackit.sqlserverflex.models.instance_flavor_entry import (
    InstanceFlavorEntry as InstanceFlavorEntry,
)
from stackit.sqlserverflex.models.instance_list_instance import (
    InstanceListInstance as InstanceListInstance,
)
from stackit.sqlserverflex.models.instance_list_user import (
    InstanceListUser as InstanceListUser,
)
from stackit.sqlserverflex.models.list_backups_response import (
    ListBackupsResponse as ListBackupsResponse,
)
from stackit.sqlserverflex.models.list_collations_response import (
    ListCollationsResponse as ListCollationsResponse,
)
from stackit.sqlserverflex.models.list_compatibility_response import (
    ListCompatibilityResponse as ListCompatibilityResponse,
)
from stackit.sqlserverflex.models.list_databases_response import (
    ListDatabasesResponse as ListDatabasesResponse,
)
from stackit.sqlserverflex.models.list_flavors_response import (
    ListFlavorsResponse as ListFlavorsResponse,
)
from stackit.sqlserverflex.models.list_instances_response import (
    ListInstancesResponse as ListInstancesResponse,
)
from stackit.sqlserverflex.models.list_metrics_response import (
    ListMetricsResponse as ListMetricsResponse,
)
from stackit.sqlserverflex.models.list_restore_jobs_response import (
    ListRestoreJobsResponse as ListRestoreJobsResponse,
)
from stackit.sqlserverflex.models.list_roles_response import (
    ListRolesResponse as ListRolesResponse,
)
from stackit.sqlserverflex.models.list_storages_response import (
    ListStoragesResponse as ListStoragesResponse,
)
from stackit.sqlserverflex.models.list_users_response import (
    ListUsersResponse as ListUsersResponse,
)
from stackit.sqlserverflex.models.list_versions_response import (
    ListVersionsResponse as ListVersionsResponse,
)
from stackit.sqlserverflex.models.mssql_database_collation import (
    MssqlDatabaseCollation as MssqlDatabaseCollation,
)
from stackit.sqlserverflex.models.mssql_database_compatibility import (
    MssqlDatabaseCompatibility as MssqlDatabaseCompatibility,
)
from stackit.sqlserverflex.models.partial_update_instance_payload import (
    PartialUpdateInstancePayload as PartialUpdateInstancePayload,
)
from stackit.sqlserverflex.models.reset_user_response import (
    ResetUserResponse as ResetUserResponse,
)
from stackit.sqlserverflex.models.restore_running_restore import (
    RestoreRunningRestore as RestoreRunningRestore,
)
from stackit.sqlserverflex.models.single_database import (
    SingleDatabase as SingleDatabase,
)
from stackit.sqlserverflex.models.single_user import SingleUser as SingleUser
from stackit.sqlserverflex.models.storage import Storage as Storage
from stackit.sqlserverflex.models.storage_range import StorageRange as StorageRange
from stackit.sqlserverflex.models.trigger_database_restore_payload import (
    TriggerDatabaseRestorePayload as TriggerDatabaseRestorePayload,
)
from stackit.sqlserverflex.models.type import Type as Type
from stackit.sqlserverflex.models.update_instance_payload import (
    UpdateInstancePayload as UpdateInstancePayload,
)
from stackit.sqlserverflex.models.update_instance_response import (
    UpdateInstanceResponse as UpdateInstanceResponse,
)
from stackit.sqlserverflex.models.user import User as User
from stackit.sqlserverflex.models.user_response_user import (
    UserResponseUser as UserResponseUser,
)
