# coding: utf-8

# flake8: noqa

"""
    STACKIT MSSQL Service API

    This is the documentation for the STACKIT MSSQL service

    The version of the OpenAPI document: 2.0.0
    Contact: support@stackit.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501 docstring might be too long


__version__ = "1.0.0"

# import apis into sdk package
from stackit.sqlserverflex.api.default_api import DefaultApi
from stackit.sqlserverflex.api_client import ApiClient

# import ApiClient
from stackit.sqlserverflex.api_response import ApiResponse
from stackit.sqlserverflex.configuration import HostConfiguration
from stackit.sqlserverflex.exceptions import (
    ApiAttributeError,
    ApiException,
    ApiKeyError,
    ApiTypeError,
    ApiValueError,
    OpenApiException,
)

# import models into sdk package
from stackit.sqlserverflex.models.acl import ACL
from stackit.sqlserverflex.models.backup import Backup
from stackit.sqlserverflex.models.backup_list_backups_response_grouped import (
    BackupListBackupsResponseGrouped,
)
from stackit.sqlserverflex.models.create_database_payload import CreateDatabasePayload
from stackit.sqlserverflex.models.create_database_response import CreateDatabaseResponse
from stackit.sqlserverflex.models.create_instance_payload import CreateInstancePayload
from stackit.sqlserverflex.models.create_instance_response import CreateInstanceResponse
from stackit.sqlserverflex.models.create_user_payload import CreateUserPayload
from stackit.sqlserverflex.models.create_user_response import CreateUserResponse
from stackit.sqlserverflex.models.data_point import DataPoint
from stackit.sqlserverflex.models.database import Database
from stackit.sqlserverflex.models.database_documentation_create_database_request_options import (
    DatabaseDocumentationCreateDatabaseRequestOptions,
)
from stackit.sqlserverflex.models.database_options import DatabaseOptions
from stackit.sqlserverflex.models.flavor import Flavor
from stackit.sqlserverflex.models.get_backup_response import GetBackupResponse
from stackit.sqlserverflex.models.get_database_response import GetDatabaseResponse
from stackit.sqlserverflex.models.get_instance_response import GetInstanceResponse
from stackit.sqlserverflex.models.get_user_response import GetUserResponse
from stackit.sqlserverflex.models.host import Host
from stackit.sqlserverflex.models.host_metric import HostMetric
from stackit.sqlserverflex.models.instance import Instance
from stackit.sqlserverflex.models.instance_documentation_acl import (
    InstanceDocumentationACL,
)
from stackit.sqlserverflex.models.instance_documentation_options import (
    InstanceDocumentationOptions,
)
from stackit.sqlserverflex.models.instance_documentation_storage import (
    InstanceDocumentationStorage,
)
from stackit.sqlserverflex.models.instance_error import InstanceError
from stackit.sqlserverflex.models.instance_flavor_entry import InstanceFlavorEntry
from stackit.sqlserverflex.models.instance_list_instance import InstanceListInstance
from stackit.sqlserverflex.models.instance_list_user import InstanceListUser
from stackit.sqlserverflex.models.list_backups_response import ListBackupsResponse
from stackit.sqlserverflex.models.list_collations_response import ListCollationsResponse
from stackit.sqlserverflex.models.list_compatibility_response import (
    ListCompatibilityResponse,
)
from stackit.sqlserverflex.models.list_databases_response import ListDatabasesResponse
from stackit.sqlserverflex.models.list_flavors_response import ListFlavorsResponse
from stackit.sqlserverflex.models.list_instances_response import ListInstancesResponse
from stackit.sqlserverflex.models.list_metrics_response import ListMetricsResponse
from stackit.sqlserverflex.models.list_restore_jobs_response import (
    ListRestoreJobsResponse,
)
from stackit.sqlserverflex.models.list_roles_response import ListRolesResponse
from stackit.sqlserverflex.models.list_storages_response import ListStoragesResponse
from stackit.sqlserverflex.models.list_users_response import ListUsersResponse
from stackit.sqlserverflex.models.list_versions_response import ListVersionsResponse
from stackit.sqlserverflex.models.mssql_database_collation import MssqlDatabaseCollation
from stackit.sqlserverflex.models.mssql_database_compatibility import (
    MssqlDatabaseCompatibility,
)
from stackit.sqlserverflex.models.partial_update_instance_payload import (
    PartialUpdateInstancePayload,
)
from stackit.sqlserverflex.models.reset_user_response import ResetUserResponse
from stackit.sqlserverflex.models.restore_running_restore import RestoreRunningRestore
from stackit.sqlserverflex.models.single_database import SingleDatabase
from stackit.sqlserverflex.models.single_user import SingleUser
from stackit.sqlserverflex.models.storage import Storage
from stackit.sqlserverflex.models.storage_range import StorageRange
from stackit.sqlserverflex.models.trigger_database_restore_payload import (
    TriggerDatabaseRestorePayload,
)
from stackit.sqlserverflex.models.type import Type
from stackit.sqlserverflex.models.update_instance_payload import UpdateInstancePayload
from stackit.sqlserverflex.models.update_instance_response import UpdateInstanceResponse
from stackit.sqlserverflex.models.user import User
from stackit.sqlserverflex.models.user_response_user import UserResponseUser
