# coding: utf-8

# flake8: noqa

"""
    Audit Log API

    API Endpoints to retrieve recorded actions and resulting changes in the system.  ### Audit Logging Changes on organizations, folders and projects and respective cloud resources are logged and collected in the audit  log.  ### API Constraints The audit log API allows to download messages from the last 90 days. The maximum duration that can be queried at  once is 24 hours. Requests are rate limited - the current maximum is 1 request per second.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501 docstring might be too long


__version__ = "1.0.0"

# import apis into sdk package
from stackit.auditlog.api.default_api import DefaultApi
from stackit.auditlog.api_client import ApiClient

# import ApiClient
from stackit.auditlog.api_response import ApiResponse
from stackit.auditlog.configuration import HostConfiguration
from stackit.auditlog.exceptions import (
    ApiAttributeError,
    ApiException,
    ApiKeyError,
    ApiTypeError,
    ApiValueError,
    OpenApiException,
)

# import models into sdk package
from stackit.auditlog.models.audit_log_entry import AuditLogEntry
from stackit.auditlog.models.context import Context
from stackit.auditlog.models.delegation_principal import DelegationPrincipal
from stackit.auditlog.models.download_folder_audit_entries200_response import (
    DownloadFolderAuditEntries200Response,
)
from stackit.auditlog.models.error import Error
from stackit.auditlog.models.initiator import Initiator
from stackit.auditlog.models.request import Request
from stackit.auditlog.models.service_account_delegation_info import (
    ServiceAccountDelegationInfo,
)
