# coding: utf-8

# flake8: noqa

"""
    STACKIT Telemetry Router API

    This API provides endpoints for managing Telemetry Routers. 

    The version of the OpenAPI document: 1beta.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "HostConfiguration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccessTokenBaseRequest",
    "AccessTokenBaseResponse",
    "ConfigFilter",
    "ConfigFilterAttributes",
    "ConfigFilterLevel",
    "ConfigFilterMatcher",
    "CreateAccessTokenPayload",
    "CreateAccessTokenResponse",
    "CreateDestinationPayload",
    "CreateTelemetryRouterPayload",
    "DestinationConfig",
    "DestinationConfigOpenTelemetry",
    "DestinationConfigOpenTelemetryBasicAuth",
    "DestinationConfigS3",
    "DestinationConfigS3AccessKey",
    "DestinationConfigType",
    "DestinationResponse",
    "GetAccessTokenResponse",
    "ListAccessTokensResponse",
    "ListDestinationsResponse",
    "ListTelemetryRoutersResponse",
    "Response4xx",
    "TelemetryRouterResponse",
    "UpdateAccessTokenPayload",
    "UpdateAccessTokenResponse",
    "UpdateDestinationPayload",
    "UpdateTelemetryRouterPayload",
]

# import apis into sdk package
from stackit.telemetryrouter.api.default_api import DefaultApi as DefaultApi
from stackit.telemetryrouter.api_client import ApiClient as ApiClient

# import ApiClient
from stackit.telemetryrouter.api_response import ApiResponse as ApiResponse
from stackit.telemetryrouter.configuration import HostConfiguration as HostConfiguration
from stackit.telemetryrouter.exceptions import ApiAttributeError as ApiAttributeError
from stackit.telemetryrouter.exceptions import ApiException as ApiException
from stackit.telemetryrouter.exceptions import ApiKeyError as ApiKeyError
from stackit.telemetryrouter.exceptions import ApiTypeError as ApiTypeError
from stackit.telemetryrouter.exceptions import ApiValueError as ApiValueError
from stackit.telemetryrouter.exceptions import OpenApiException as OpenApiException

# import models into sdk package
from stackit.telemetryrouter.models.access_token_base_request import (
    AccessTokenBaseRequest as AccessTokenBaseRequest,
)
from stackit.telemetryrouter.models.access_token_base_response import (
    AccessTokenBaseResponse as AccessTokenBaseResponse,
)
from stackit.telemetryrouter.models.config_filter import ConfigFilter as ConfigFilter
from stackit.telemetryrouter.models.config_filter_attributes import (
    ConfigFilterAttributes as ConfigFilterAttributes,
)
from stackit.telemetryrouter.models.config_filter_level import (
    ConfigFilterLevel as ConfigFilterLevel,
)
from stackit.telemetryrouter.models.config_filter_matcher import (
    ConfigFilterMatcher as ConfigFilterMatcher,
)
from stackit.telemetryrouter.models.create_access_token_payload import (
    CreateAccessTokenPayload as CreateAccessTokenPayload,
)
from stackit.telemetryrouter.models.create_access_token_response import (
    CreateAccessTokenResponse as CreateAccessTokenResponse,
)
from stackit.telemetryrouter.models.create_destination_payload import (
    CreateDestinationPayload as CreateDestinationPayload,
)
from stackit.telemetryrouter.models.create_telemetry_router_payload import (
    CreateTelemetryRouterPayload as CreateTelemetryRouterPayload,
)
from stackit.telemetryrouter.models.destination_config import (
    DestinationConfig as DestinationConfig,
)
from stackit.telemetryrouter.models.destination_config_open_telemetry import (
    DestinationConfigOpenTelemetry as DestinationConfigOpenTelemetry,
)
from stackit.telemetryrouter.models.destination_config_open_telemetry_basic_auth import (
    DestinationConfigOpenTelemetryBasicAuth as DestinationConfigOpenTelemetryBasicAuth,
)
from stackit.telemetryrouter.models.destination_config_s3 import (
    DestinationConfigS3 as DestinationConfigS3,
)
from stackit.telemetryrouter.models.destination_config_s3_access_key import (
    DestinationConfigS3AccessKey as DestinationConfigS3AccessKey,
)
from stackit.telemetryrouter.models.destination_config_type import (
    DestinationConfigType as DestinationConfigType,
)
from stackit.telemetryrouter.models.destination_response import (
    DestinationResponse as DestinationResponse,
)
from stackit.telemetryrouter.models.get_access_token_response import (
    GetAccessTokenResponse as GetAccessTokenResponse,
)
from stackit.telemetryrouter.models.list_access_tokens_response import (
    ListAccessTokensResponse as ListAccessTokensResponse,
)
from stackit.telemetryrouter.models.list_destinations_response import (
    ListDestinationsResponse as ListDestinationsResponse,
)
from stackit.telemetryrouter.models.list_telemetry_routers_response import (
    ListTelemetryRoutersResponse as ListTelemetryRoutersResponse,
)
from stackit.telemetryrouter.models.response4xx import Response4xx as Response4xx
from stackit.telemetryrouter.models.telemetry_router_response import (
    TelemetryRouterResponse as TelemetryRouterResponse,
)
from stackit.telemetryrouter.models.update_access_token_payload import (
    UpdateAccessTokenPayload as UpdateAccessTokenPayload,
)
from stackit.telemetryrouter.models.update_access_token_response import (
    UpdateAccessTokenResponse as UpdateAccessTokenResponse,
)
from stackit.telemetryrouter.models.update_destination_payload import (
    UpdateDestinationPayload as UpdateDestinationPayload,
)
from stackit.telemetryrouter.models.update_telemetry_router_payload import (
    UpdateTelemetryRouterPayload as UpdateTelemetryRouterPayload,
)
