# coding: utf-8

# flake8: noqa

"""
    STACKIT Application Load Balancer Web Application Firewall API

    Generate a Web Application Firewall (WAF) to use with Application Load Balancers (ALB). The name of the WAF configuration is used in the listener of the ALB. This will activate the WAF for that ALB. An ALB with a WAF can have Managed Rule Set (MRS) and in addition can have Custom Rule Group (CRG). To create a WAF one first needs to create all the configurations that are referenced in the WAF configuration. Currently this only consists of a rule configuration, which is written in Seclang. Once all configurations are created and referenced in the WAF configuration it can be used with an ALB. Currently updating a WAF configuration will not update an existing ALB until the Load Balancer VMs are restarted.

    The version of the OpenAPI document: 1beta.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "HostConfiguration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Behaviour",
    "CRGConfigQuota",
    "CRGUsage",
    "Condition",
    "ConditionOperator",
    "ConditionVariable",
    "CreateCustomRule",
    "CreateCustomRuleGroupPayload",
    "CreateManagedRuleSetPayload",
    "CreateWAFPayload",
    "GetBehaviour",
    "GetCustomRule",
    "GetCustomRuleGroupResponse",
    "GetLimitedManagedRuleSetResponse",
    "GetManagedRuleSetResponse",
    "GetQuotaResponse",
    "GetWAFResponse",
    "GoogleProtobufAny",
    "ListCustomRuleGroupResponse",
    "ListManagedRuleSetResponse",
    "ListWAFResponse",
    "MRSConfigQuota",
    "MRSRule",
    "MRSRuleGroup",
    "MRSUsage",
    "PatchMRSRule",
    "PatchMRSRuleGroup",
    "PatchManagedRuleSetPayload",
    "Quotas",
    "Status",
    "UpdateWAFPayload",
    "WAFConfigQuota",
    "WAFUsage",
    "WAFUsageItem",
]

# import apis into sdk package
from stackit.albwaf.api.default_api import DefaultApi as DefaultApi
from stackit.albwaf.api_client import ApiClient as ApiClient

# import ApiClient
from stackit.albwaf.api_response import ApiResponse as ApiResponse
from stackit.albwaf.configuration import HostConfiguration as HostConfiguration
from stackit.albwaf.exceptions import ApiAttributeError as ApiAttributeError
from stackit.albwaf.exceptions import ApiException as ApiException
from stackit.albwaf.exceptions import ApiKeyError as ApiKeyError
from stackit.albwaf.exceptions import ApiTypeError as ApiTypeError
from stackit.albwaf.exceptions import ApiValueError as ApiValueError
from stackit.albwaf.exceptions import OpenApiException as OpenApiException

# import models into sdk package
from stackit.albwaf.models.behaviour import Behaviour as Behaviour
from stackit.albwaf.models.condition import Condition as Condition
from stackit.albwaf.models.condition_operator import (
    ConditionOperator as ConditionOperator,
)
from stackit.albwaf.models.condition_variable import (
    ConditionVariable as ConditionVariable,
)
from stackit.albwaf.models.create_custom_rule import (
    CreateCustomRule as CreateCustomRule,
)
from stackit.albwaf.models.create_custom_rule_group_payload import (
    CreateCustomRuleGroupPayload as CreateCustomRuleGroupPayload,
)
from stackit.albwaf.models.create_managed_rule_set_payload import (
    CreateManagedRuleSetPayload as CreateManagedRuleSetPayload,
)
from stackit.albwaf.models.create_waf_payload import (
    CreateWAFPayload as CreateWAFPayload,
)
from stackit.albwaf.models.crg_config_quota import CRGConfigQuota as CRGConfigQuota
from stackit.albwaf.models.crg_usage import CRGUsage as CRGUsage
from stackit.albwaf.models.get_behaviour import GetBehaviour as GetBehaviour
from stackit.albwaf.models.get_custom_rule import GetCustomRule as GetCustomRule
from stackit.albwaf.models.get_custom_rule_group_response import (
    GetCustomRuleGroupResponse as GetCustomRuleGroupResponse,
)
from stackit.albwaf.models.get_limited_managed_rule_set_response import (
    GetLimitedManagedRuleSetResponse as GetLimitedManagedRuleSetResponse,
)
from stackit.albwaf.models.get_managed_rule_set_response import (
    GetManagedRuleSetResponse as GetManagedRuleSetResponse,
)
from stackit.albwaf.models.get_quota_response import (
    GetQuotaResponse as GetQuotaResponse,
)
from stackit.albwaf.models.get_waf_response import GetWAFResponse as GetWAFResponse
from stackit.albwaf.models.google_protobuf_any import (
    GoogleProtobufAny as GoogleProtobufAny,
)
from stackit.albwaf.models.list_custom_rule_group_response import (
    ListCustomRuleGroupResponse as ListCustomRuleGroupResponse,
)
from stackit.albwaf.models.list_managed_rule_set_response import (
    ListManagedRuleSetResponse as ListManagedRuleSetResponse,
)
from stackit.albwaf.models.list_waf_response import ListWAFResponse as ListWAFResponse
from stackit.albwaf.models.mrs_config_quota import MRSConfigQuota as MRSConfigQuota
from stackit.albwaf.models.mrs_rule import MRSRule as MRSRule
from stackit.albwaf.models.mrs_rule_group import MRSRuleGroup as MRSRuleGroup
from stackit.albwaf.models.mrs_usage import MRSUsage as MRSUsage
from stackit.albwaf.models.patch_managed_rule_set_payload import (
    PatchManagedRuleSetPayload as PatchManagedRuleSetPayload,
)
from stackit.albwaf.models.patch_mrs_rule import PatchMRSRule as PatchMRSRule
from stackit.albwaf.models.patch_mrs_rule_group import (
    PatchMRSRuleGroup as PatchMRSRuleGroup,
)
from stackit.albwaf.models.quotas import Quotas as Quotas
from stackit.albwaf.models.status import Status as Status
from stackit.albwaf.models.update_waf_payload import (
    UpdateWAFPayload as UpdateWAFPayload,
)
from stackit.albwaf.models.waf_config_quota import WAFConfigQuota as WAFConfigQuota
from stackit.albwaf.models.waf_usage import WAFUsage as WAFUsage
from stackit.albwaf.models.waf_usage_item import WAFUsageItem as WAFUsageItem
