# coding: utf-8

# flake8: noqa
"""
    STACKIT Edge Cloud API

    This API provides endpoints for managing STACKIT Edge Cloud instances.

    The version of the OpenAPI document: 1beta1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from stackit.edge.models.bad_request import BadRequest
from stackit.edge.models.create_instance_payload import CreateInstancePayload
from stackit.edge.models.instance import Instance
from stackit.edge.models.instance_list import InstanceList
from stackit.edge.models.kubeconfig import Kubeconfig
from stackit.edge.models.plan import Plan
from stackit.edge.models.plan_list import PlanList
from stackit.edge.models.token import Token
from stackit.edge.models.unauthorized_request import UnauthorizedRequest
from stackit.edge.models.update_instance_by_name_payload import (
    UpdateInstanceByNamePayload,
)
from stackit.edge.models.update_instance_payload import UpdateInstancePayload
from stackit.edge.models.user import User
