# coding: utf-8

"""
    STACKIT Telemetry Router API

    This API provides endpoints for managing Telemetry Routers. 

    The version of the OpenAPI document: 1beta.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class DestinationConfigType(str, Enum):
    """
    Type of the destination.
    """

    """
    allowed enum values
    """
    OPENTELEMETRY = "OpenTelemetry"
    S3 = "S3"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DestinationConfigType from a JSON string"""
        return cls(json.loads(json_str))
