# coding: utf-8

"""
    STACKIT Telemetry Router API

    This API provides endpoints for managing Telemetry Routers. 

    The version of the OpenAPI document: 1beta.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from pydantic_core import to_jsonable_python
from typing_extensions import Annotated, Self

from stackit.telemetryrouter.models.destination_config import DestinationConfig


class DestinationResponse(BaseModel):
    """
    DestinationResponse
    """  # noqa: E501

    config: DestinationConfig
    creation_time: datetime = Field(description="The point in time the resource was created.", alias="creationTime")
    credential_type: StrictStr = Field(description="The credential type for the resource.", alias="credentialType")
    description: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(
        default=None,
        description="The description is a longer text chosen by the user to provide more context for the resource.",
    )
    display_name: Annotated[str, Field(min_length=1, strict=True, max_length=32)] = Field(
        description="The display name is a short name chosen by the user to identify the resource.", alias="displayName"
    )
    id: UUID = Field(description="A auto generated unique id which identifies the resource.")
    status: StrictStr = Field(description="The current status of the resource.")
    __properties: ClassVar[List[str]] = [
        "config",
        "creationTime",
        "credentialType",
        "description",
        "displayName",
        "id",
        "status",
    ]

    @field_validator("creation_time", mode="before")
    def creation_time_change_year_zero_to_one(cls, value):
        """Workaround which prevents year 0 issue"""
        if isinstance(value, str):
            # Check for year "0000" at the beginning of the string
            # This assumes common date formats like YYYY-MM-DDTHH:MM:SS+00:00 or YYYY-MM-DDTHH:MM:SSZ
            if value.startswith("0000-01-01T") and re.match(
                r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\+\d{2}:\d{2}|Z)$", value
            ):
                # Workaround: Replace "0000" with "0001"
                return "0001" + value[4:]  # Take "0001" and append the rest of the string
        return value

    @field_validator("credential_type")
    def credential_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["bearerToken", "basicAuth", "accessKey"]):
            raise ValueError("must be one of enum values ('bearerToken', 'basicAuth', 'accessKey')")
        return value

    @field_validator("display_name")
    def display_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-zA-Z0-9][a-zA-Z0-9 \-]*$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9][a-zA-Z0-9 \-]*$/")
        return value

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["reconciling", "active", "deleting"]):
            raise ValueError("must be one of enum values ('reconciling', 'active', 'deleting')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DestinationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict["config"] = self.config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DestinationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "config": DestinationConfig.from_dict(obj["config"]) if obj.get("config") is not None else None,
                "creationTime": obj.get("creationTime"),
                "credentialType": obj.get("credentialType"),
                "description": obj.get("description"),
                "displayName": obj.get("displayName"),
                "id": obj.get("id"),
                "status": obj.get("status"),
            }
        )
        return _obj
