# coding: utf-8

"""
    STACKIT Telemetry Router API

    This API provides endpoints for managing Telemetry Routers. 

    The version of the OpenAPI document: 1beta.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from stackit.telemetryrouter.models.get_access_token_response import (
    GetAccessTokenResponse,
)


class ListAccessTokensResponse(BaseModel):
    """
    ListAccessTokensResponse
    """  # noqa: E501

    access_tokens: List[GetAccessTokenResponse] = Field(alias="accessTokens")
    next_page_token: Optional[StrictStr] = Field(
        default=None, description="A token to retrieve the next page of results.", alias="nextPageToken"
    )
    __properties: ClassVar[List[str]] = ["accessTokens", "nextPageToken"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListAccessTokensResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in access_tokens (list)
        _items = []
        if self.access_tokens:
            for _item_access_tokens in self.access_tokens:
                if _item_access_tokens:
                    _items.append(_item_access_tokens.to_dict())
            _dict["accessTokens"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListAccessTokensResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "accessTokens": (
                    [GetAccessTokenResponse.from_dict(_item) for _item in obj["accessTokens"]]
                    if obj.get("accessTokens") is not None
                    else None
                ),
                "nextPageToken": obj.get("nextPageToken"),
            }
        )
        return _obj
