# coding: utf-8

# flake8: noqa
"""
    STACKIT Telemetry Link API

    This API provides endpoints for managing Telemetry Links. The Telemetry Link enables Log Routing towards a defined Telemetry Router. 

    The version of the OpenAPI document: 1beta.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from stackit.telemetrylink.models.create_or_update_folder_telemetry_link_payload import (
    CreateOrUpdateFolderTelemetryLinkPayload,
)
from stackit.telemetrylink.models.create_or_update_organization_telemetry_link_payload import (
    CreateOrUpdateOrganizationTelemetryLinkPayload,
)
from stackit.telemetrylink.models.create_or_update_project_telemetry_link_payload import (
    CreateOrUpdateProjectTelemetryLinkPayload,
)
from stackit.telemetrylink.models.partial_update_folder_telemetry_link_payload import (
    PartialUpdateFolderTelemetryLinkPayload,
)
from stackit.telemetrylink.models.partial_update_organization_telemetry_link_payload import (
    PartialUpdateOrganizationTelemetryLinkPayload,
)
from stackit.telemetrylink.models.partial_update_project_telemetry_link_payload import (
    PartialUpdateProjectTelemetryLinkPayload,
)
from stackit.telemetrylink.models.response4xx import Response4xx
from stackit.telemetrylink.models.telemetry_link_request import TelemetryLinkRequest
from stackit.telemetrylink.models.telemetry_link_response import TelemetryLinkResponse
