name: "Labeler"
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    name: "Labeler"
    runs-on: ubuntu-latest
    steps:
      # Re-uses the labeler config from the Go SDK, so we only need to maintain one single config file
      - name: Fetch labeler config from STACKIT Go SDK
        run: |
          curl -sSL -o remote-labeler.yml https://raw.githubusercontent.com/stackitcloud/stackit-sdk-go/feat/labeler/.github/labeler.yml 
      - name: Labeler action
        uses: actions/labeler@v6
        with:
          configuration-path: "remote-labeler.yml"
          sync-labels: false
